spring.application.name=product-service
server.port=8082

#postgresql
spring.datasource.url=jdbc:postgresql://product-db:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=postgres

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=my-super-secret-key-for-jwt-authentication-123456789